version: '3.8'
services: 
  oracle-db:
    image: container-registry.oracle.com/database/express
    ports:
      - 55000:5500
      - 15210:1521
    environment:
      ORACLE_PWD: 123456
    volumes:
      - d:/local_project/oracledb:/opt/oracle/oradata
    networks:
      - ATVBM
networks:
  ATVBM: